
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.centroauto.reservaturnos.vista;

import com.centroauto.reservaturnos.dao.CiudadesDao;
import com.centroauto.reservaturnos.dao.DepartamentosDao;
import com.centroauto.reservaturnos.dao.SucursalesDao;
import com.centroauto.reservaturnos.dto.CiudadesDTO;
import com.centroauto.reservaturnos.dto.SucursalesDTO;
import com.centroauto.reservaturnos.entidades.Departamentos;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jlrodriguez
 */
public class WinSucursalesForm extends javax.swing.JDialog {
    private SucursalesDao sucursalesDao;
    /**
     * Maneja el modo de la pantalla (T: modo inserción, F: modo actualización)
     */
    private boolean modoNuevo;    
    /**
     * Objeto que contiene la información de la sucursal cuando se va a modificar
     */
    private SucursalesDTO sucursalAnt;
    
    private WinSucursalesPpal sucursalesPpal;
    
    private DepartamentosDao deptoDao;
    
    private CiudadesDao ciudadDao;
    
    /**
     * Creates new form WinSucursalesForm
     */
    public WinSucursalesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public WinSucursalesForm(WinSucursalesPpal sucursalesPpal,
                            SucursalesDTO sucursalAnt, boolean modoNuevo){
        this.sucursalesPpal = sucursalesPpal;
        this.sucursalAnt = sucursalAnt;
        this.modoNuevo = modoNuevo;  
        this.sucursalesDao = new SucursalesDao();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //Llenar lista de departamentos
        this.llenarDepartamentos();
        
        //Validar modo Edición
        if(!this.modoNuevo){
            this.llenarFormulario();
        }
    }    
    public void llenarFormulario(){
        this.txtNomSucursal.setText(sucursalAnt.getNomSucursal());
        this.txtDireccion.setText(sucursalAnt.getDirSucursal());
        this.txtTelefono.setText(sucursalAnt.getTelSucursal().toString());
        this.cmbDepartamento.setSelectedItem(sucursalAnt.getIdDepto()+" - "+
                sucursalAnt.getNomDepto());
    }
    
    public void llenarDepartamentos(){
        try{
            deptoDao = new DepartamentosDao();
            List<Departamentos> lstDeptos = deptoDao.consultarDepartamentos();
            this.cmbDepartamento.addItem("0 - Seleccione");
            for(Departamentos d: lstDeptos){
                this.cmbDepartamento.addItem(d.getIdDepto()+" - "+d.getNomDepto());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void llenarCiudades(){
        try{      
            ciudadDao = new CiudadesDao();
            Integer idDepto = 
                    Integer.parseInt(this.cmbDepartamento.getSelectedItem().toString()
                            .split("-")[0].trim());   
            cmbCiudad.removeAllItems();
            cmbCiudad.addItem("0 - Seleccione");
            if(idDepto > 0){
                List<CiudadesDTO> lstCiudades = ciudadDao.consultarCiudadesPorDepto(idDepto);
               
                for(CiudadesDTO c : lstCiudades){
                    this.cmbCiudad.addItem(c.getIdCiudad()+" - "+c.getNomCiudad());
                }
            }    
            //Validar modo Edición
            if(!this.modoNuevo){
                this.cmbCiudad.setSelectedItem(sucursalAnt.getIdCiudad()+" - "+
                        sucursalAnt.getNomCiudad());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomSucursal1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNomSucursal = new javax.swing.JLabel();
        txtNomSucursal = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        lblCiudad = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        lblNomSucursal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomSucursal1.setText("Nombre: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Crear/Modificar Sucursal");

        lblNomSucursal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomSucursal.setText("Nombre: ");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDireccion.setText("Dirección: ");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefono.setText("Teléfono: ");

        lblDepartamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDepartamento.setText("Departamento: ");

        cmbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartamentoActionPerformed(evt);
            }
        });

        lblCiudad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCiudad.setText("Ciudad: ");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomSucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomSucursal)
                    .addComponent(txtNomSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(lblDepartamento)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
        llenarCiudades();
    }//GEN-LAST:event_cmbDepartamentoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Validar que los campos obligatorios hayan sido diligenciados
        if(this.txtNomSucursal.getText() == null || this.txtDireccion.getText() == null
                || Integer.parseInt(this.cmbCiudad.getSelectedItem().toString()
                            .split("-")[0].trim()) == 0){
            JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Armar objeto SucursalesDTO
        SucursalesDTO s;
        if(this.modoNuevo){
            s = new SucursalesDTO();
        }else{
            s = sucursalAnt;
        }
        s.setNomSucursal(this.txtNomSucursal.getText());
        s.setDirSucursal(this.txtDireccion.getText());
        s.setTelSucursal(Long.parseLong(this.txtTelefono.getText()));
        s.setIdCiudad(Integer.parseInt(this.cmbCiudad.getSelectedItem().toString()
                            .split("-")[0].trim()));
        try{
            if(this.modoNuevo){
                sucursalesDao.insertarSucursal(s);
            }else{
                sucursalesDao.actualizarSucursal(s);
            }
            this.setVisible(false);
            this.sucursalesPpal.consultarSucursales();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinSucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinSucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinSucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinSucursalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinSucursalesForm dialog = new WinSucursalesForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNomSucursal;
    private javax.swing.JLabel lblNomSucursal1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNomSucursal;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
